#!/bin/bash

: ${ZENDIR:="$HOME/.zentracker"}
file="$ZENDIR/"`date "+%Y-%m-%d"`
if [ ! -f "$file" ]; then
    touch "$file"
    exit 1
fi

text=`cat $file`

function convert_min_to_hour()
{
    read v
    ((hour=$v/60))
    ((min=$v-$hour*60))
    echo ${hour}h:${min}m
}

function do_format()
{
    while read IN; do
        echo -e $(echo "$IN" | cut -d' ' -f 1)"\t"$(echo "$IN" | cut -d' ' -f 2 | convert_min_to_hour)
    done <<< "$1"
}

function on_by_hours()
{
    local v=`echo "$text" | cut -d : -f 1 | sort | uniq -c | sort -nr | sed -E 's/^ *([0-9]+) ([0-9]+) */\2 \1/' | sort`
    echo "$v" | tr '\n' '\t'
    echo
}

function by_application()
{
    local v=`echo "$text" | cut -f 2 | sort | uniq -c | sort -nr | sed -E 's/^ *([0-9]+) (.+) */\2 \1/'`
    do_format "$v"
}

function total_time()
{
    wc -l <<< "$text" | convert_min_to_hour
}

function details()
{
    echo "$text"
}

p="ZenTracker Daily Report\n"
p="$p""[TOTAL TIME] `total_time`""\n"
p="$p""[BY HOURS] "
p="$p`on_by_hours`""\n"
p="$p""[BY APPLICATIONS] ""\n"
p="$p`by_application`""\n"
p="$p""[DETAILS]""\n"
p="$p`details`"
echo -e "$p" | less
