#!/bin/bash

: ${ZENDIR:="$HOME/.zentracker"}
file="$ZENDIR/"`date "+%Y-%m-%d"`
if [ ! -f "$file" ]; then
    touch "$file"
    exit 1
fi

text=`cat $file`

function colorize() {
    if [ -t 1 ]; then
        case "$1" in
            underline)
                local color_start=$(tput sgr 0 1);;
            bold)
                local color_start=$(tput bold);;
            red)
                local color_start=$(tput setaf 1);;
            green)
                local color_start=$(tput setaf 2);;
            yellow)
                local color_start=$(tput setaf 3);;
            blue)
                local color_start=$(tput setaf 4);;
            purple)
                local color_start=$(tput setaf 5);;
            cyan)
                local color_start=$(tput setaf 6);;
            white)
                local color_start=$(tput setaf 7);;
        esac

        shift
        local color_reset=$(tput sgr0)

        echo "${color_start}$*${color_reset}"
    else
        echo "$*"
    fi
}

function convert_min_to_hour()
{
    read v
    ((hour=$v/60))
    ((min=$v-$hour*60))
    echo ${hour}h:${min}m
}

function do_format()
{
    while read IN; do
        echo -e $(echo "$IN" | cut -d' ' -f 1)"\t"$(echo "$IN" | cut -d' ' -f 2 | convert_min_to_hour)
    done <<< "$1"
}

function on_by_hours()
{
    local v=`echo "$text" | cut -d : -f 1 | sort | uniq -c | sort -nr | sed -E 's/^ *([0-9]+) ([0-9]+) */\2 \1/' | sort`
    echo "$v" | tr '\n' '\t'
    echo
}

function by_application()
{
    local v=`echo "$text" | cut -f 2 | sort | uniq -c | sort -nr | sed -E 's/^ *([0-9]+) (.+) */\2 \1/'`
    do_format "$v"
}

function total_time()
{
    wc -l <<< "$text" | convert_min_to_hour
}

function details()
{
    echo "$text"
}

p=`colorize red "ZenTracker Daily Report\n"`
p=$p`colorize green "[TOTAL TIME] "`
p=$p`total_time`"\n"
p=$p`colorize green "[BY HOURS] "`
p=$p`on_by_hours`"\n"
p=$p`colorize green "[BY APPLICATIONS]\n"`
p=$p`by_application`"\n"
p=$p`colorize green "[DETAILS]\n"`
p=$p`details`
echo -e "$p" | less
